<!-- /// ICONS MODAL ///-->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Seleccione un &iacute;cono</i></h4>
      </div>
      <div class="modal-body menuIcons">
        <ul>
          <li><i class="fa fa-glass"></i></li>
          <li><i class="fa fa-music"></i></li>
          <li><i class="fa fa-search"></i></li>
          <li><i class="fa fa-envelope-o"></i></li>
          <li><i class="fa fa-heart"></i></li>
          <li><i class="fa fa-star"></i></li>
          <li><i class="fa fa-star-o"></i></li>
          <li><i class="fa fa-user"></i></li>
          <li><i class="fa fa-film"></i></li>
          <li><i class="fa fa-th-large"></i></li>
          <li><i class="fa fa-th"></i></li>
          <li><i class="fa fa-th-list"></i></li>
          <li><i class="fa fa-check"></i></li>
          <li><i class="fa fa-close"></i></li>
          <li><i class="fa fa-times"></i></li>
          <li><i class="fa fa-search-plus"></i></li>
          <li><i class="fa fa-search-minus"></i></li>
          <li><i class="fa fa-power-off"></i></li>
          <li><i class="fa fa-signal"></i></li>
          <li><i class="fa fa-cog"></i></li>
          <li><i class="fa fa-trash-o"></i></li>
          <li><i class="fa fa-home"></i></li>
          <li><i class="fa fa-file-o"></i></li>
          <li><i class="fa fa-clock-o"></i></li>
          <li><i class="fa fa-road"></i></li>
          <li><i class="fa fa-download"></i></li>
          <li><i class="fa fa-arrow-circle-o-down"></i></li>
          <li><i class="fa fa-arrow-circle-o-up"></i></li>
          <li><i class="fa fa-inbox"></i></li>
          <li><i class="fa fa-play-circle-o"></i></li>
          <li><i class="fa fa-repeat"></i></li>
          <li><i class="fa fa-refresh"></i></li>
          <li><i class="fa fa-list-alt"></i></li>
          <li><i class="fa fa-lock"></i></li>
          <li><i class="fa fa-flag"></i></li>
          <li><i class="fa fa-headphones"></i></li>
          <li><i class="fa fa-volume-off"></i></li>
          <li><i class="fa fa-volume-down"></i></li>
          <li><i class="fa fa-volume-up"></i></li>
          <li><i class="fa fa-qrcode"></i></li>
          <li><i class="fa fa-barcode"></i></li>
          <li><i class="fa fa-tag"></i></li>
          <li><i class="fa fa-tags"></i></li>
          <li><i class="fa fa-book"></i></li>
          <li><i class="fa fa-bookmark"></i></li>
          <li><i class="fa fa-print"></i></li>
          <li><i class="fa fa-camera"></i></li>
          <li><i class="fa fa-font"></i></li>
          <li><i class="fa fa-bold"></i></li>
          <li><i class="fa fa-italic"></i></li>
          <li><i class="fa fa-text-height"></i></li>
          <li><i class="fa fa-text-width"></i></li>
          <li><i class="fa fa-align-left"></i></li>
          <li><i class="fa fa-align-center"></i></li>
          <li><i class="fa fa-align-right"></i></li>
          <li><i class="fa fa-align-justify"></i></li>
          <li><i class="fa fa-list"></i></li>
          <li><i class="fa fa-dedent"></i></li>
          <li><i class="fa fa-indent"></i></li>
          <li><i class="fa fa-video-camera"></i></li>
          <li><i class="fa fa-photo"></i></li>
          <li><i class="fa fa-pencil"></i></li>
          <li><i class="fa fa-map-marker"></i></li>
          <li><i class="fa fa-adjust"></i></li>
          <li><i class="fa fa-tint"></i></li>
          <li><i class="fa fa-edit"></i></li>
          <li><i class="fa fa-share-square-o"></i></li>
          <li><i class="fa fa-check-square-o"></i></li>
          <li><i class="fa fa-arrows"></i></li>
          <li><i class="fa fa-step-backward"></i></li>
          <li><i class="fa fa-fast-backward"></i></li>
          <li><i class="fa fa-backward"></i></li>
          <li><i class="fa fa-play"></i></li>
          <li><i class="fa fa-pause"></i></li>
          <li><i class="fa fa-stop"></i></li>
          <li><i class="fa fa-forward"></i></li>
          <li><i class="fa fa-fast-forward"></i></li>
          <li><i class="fa fa-step-forward"></i></li>
          <li><i class="fa fa-eject"></i></li>
          <li><i class="fa fa-chevron-left"></i></li>
          <li><i class="fa fa-chevron-right"></i></li>
          <li><i class="fa fa-plus-circle"></i></li>
          <li><i class="fa fa-minus-circle"></i></li>
          <li><i class="fa fa-times-circle"></i></li>
          <li><i class="fa fa-check-circle"></i></li>
          <li><i class="fa fa-question-circle"></i></li>
          <li><i class="fa fa-info-circle"></i></li>
          <li><i class="fa fa-crosshairs"></i></li>
          <li><i class="fa fa-times-circle-o"></i></li>
          <li><i class="fa fa-check-circle-o"></i></li>
          <li><i class="fa fa-ban"></i></li>
          <li><i class="fa fa-arrow-left"></i></li>
          <li><i class="fa fa-arrow-right"></i></li>
          <li><i class="fa fa-arrow-up"></i></li>
          <li><i class="fa fa-arrow-down"></i></li>
          <li><i class="fa fa-share"></i></li>
          <li><i class="fa fa-expand"></i></li>
          <li><i class="fa fa-compress"></i></li>
          <li><i class="fa fa-plus"></i></li>
          <li><i class="fa fa-minus"></i></li>
          <li><i class="fa fa-asterisk"></i></li>
          <li><i class="fa fa-exclamation-circle"></i></li>
          <li><i class="fa fa-gift"></i></li>
          <li><i class="fa fa-leaf"></i></li>
          <li><i class="fa fa-fire"></i></li>
          <li><i class="fa fa-eye"></i></li>
          <li><i class="fa fa-eye-slash"></i></li>
          <li><i class="fa fa-warning"></i></li>
          <li><i class="fa fa-plane"></i></li>
          <li><i class="fafa-calendar"></i></li>
          <li><i class="fa fa-random"></i></li>
          <li><i class="fa fa-comment"></i></li>
          <li><i class="fa fa-magnet"></i></li>
          <li><i class="fa fa-chevron-up"></i></li>
          <li><i class="fa fa-chevron-down"></i></li>
          <li><i class="fa fa-retweet"></i></li>
          <li><i class="fa fa-shopping-cart"></i></li>
          <li><i class="fa fa-folder"></i></li>
          <li><i class="fa fa-folder-open"></i></li>
          <li><i class="fa fa-arrows-v"></i></li>
          <li><i class="fa fa-arrows-h"></i></li>
          <li><i class="fa fa-bar-chart-o"></i></li>
          <li><i class="fa fa-twitter-square"></i></li>
          <li><i class="fa fa-facebook-square"></i></li>
          <li><i class="fa fa-camera-retro"></i></li>
          <li><i class="fa fa-key"></i></li>
          <li><i class="fa fa-cogs"></i></li>
          <li><i class="fa fa-comments"></i></li>
          <li><i class="fa fa-thumbs-o-up"></i></li>
          <li><i class="fa fa-thumbs-o-down"></i></li>
          <li><i class="fa fa-star-half"></i></li>
          <li><i class="fa fa-heart-o"></i></li>
          <li><i class="fa fa-sign-out"></i></li>
          <li><i class="fa fa-linkedin-square"></i></li>
          <li><i class="fa fa-thumb-tack"></i></li>
          <li><i class="fa fa-external-link"></i></li>
          <li><i class="fa fa-sign-in"></i></li>
          <li><i class="fa fa-trophy"></i></li>
          <li><i class="fa fa-github-square"></i></li>
          <li><i class="fa fa-upload"></i></li>
          <li><i class="fa fa-lemon-o"></i></li>
          <li><i class="fa fa-phone"></i></li>
          <li><i class="fa fa-square-o"></i></li>
          <li><i class="fa fa-bookmark-o"></i></li>
          <li><i class="fa fa-phone-square"></i></li>
          <li><i class="fa fa-twitter"></i></li>
          <li><i class="fa fa-facebook"></i></li>
          <li><i class="fa fa-github"></i></li>
          <li><i class="fa fa-unlock"></i></li>
          <li><i class="fa fa-credit-card"></i></li>
          <li><i class="fa fa-rss"></i></li>
          <li><i class="fa fa-hdd-o"></i></li>
          <li><i class="fa fa-bullhorn"></i></li>
          <li><i class="fa fa-bell"></i></li>
          <li><i class="fa fa-certificate"></i></li>
          <li><i class="fa fa-hand-o-right"></i></li>
          <li><i class="fa fa-hand-o-left"></i></li>
          <li><i class="fa fa-hand-o-up"></i></li>
          <li><i class="fa fa-hand-o-down"></i></li>
          <li><i class="fa fa-arrow-circle-left"></i></li>
          <li><i class="fa fa-arrow-circle-right"></i></li>
          <li><i class="fa fa-arrow-circle-up"></i></li>
          <li><i class="fa fa-arrow-circle-down"></i></li>
          <li><i class="fa fa-globe"></i></li>
          <li><i class="fa fa-wrench"></i></li>
          <li><i class="fa fa-tasks"></i></li>
          <li><i class="fa fa-filter"></i></li>
          <li><i class="fa fa-briefcase"></i></li>
          <li><i class="fa fa-arrows-alt"></i></li>
          <li><i class="fa fa-users"></i></li>
          <li><i class="fa fa-link"></i></li>
          <li><i class="fa fa-cloud"></i></li>
          <li><i class="fa fa-flask"></i></li>
          <li><i class="fa fa-scissors"></i></li>
          <li><i class="fa fa-files-o"></i></li>
          <li><i class="fa fa-paperclip"></i></li>
          <li><i class="fa fa-floppy-o"></i></li>
          <li><i class="fa fa-square"></i></li>
          <li><i class="fa fa-bars"></i></li>
          <li><i class="fa fa-list-ul"></i></li>
          <li><i class="fa fa-list-ol"></i></li>
        </ul>

      </div>
      <div class="modal-footer">
        <button type="button" name="button" class="btn mainbtn"> Agregar</button>
        <button type="button" name="button" class="btn mainbtn mainbtnred" data-dismiss="modal">Cancelar</button><br>
      </div>
    </div>
  </div>
</div><!-- /// ICONS MODAL /// -->
